name: darood_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  control_style: ^0.1.0
  supabase_flutter: ^2.9.1
  shared_preferences: ^2.5.3
  flutter_advanced_drawer: ^1.5.0
  image_picker: ^1.2.0
  flutter_map: ^8.2.1
  geolocator: ^14.0.2
  latlong2: ^0.9.1
  http: ^1.5.0
  flutter_local_notifications: ^19.4.1
  workmanager: ^0.9.0+3
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/app_logo.png"
